FROM python:3.10-slim

WORKDIR /app

COPY requirements-api.txt /app/requirements-api.txt
RUN apt-get update \
    && apt-get install -y --no-install-recommends build-essential curl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && pip install --no-cache-dir -r /app/requirements-api.txt

COPY src /app/src
COPY data/raw/movies.dat /app/data/raw/movies.dat

EXPOSE 8000

CMD ["uvicorn", "src.serving.app:app", "--host", "0.0.0.0", "--port", "8000"]
