FROM python:3.10-slim

RUN apt-get update \
    && apt-get install -y --no-install-recommends curl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir mlflow==2.14.3 psycopg2-binary==2.9.9

WORKDIR /mlflow
EXPOSE 5000
