global:
  scrape_interval: 15s

scrape_configs:
  - job_name: movie-recommender-api
    metrics_path: /metrics
    static_configs:
      - targets: ["api:8000"]

  - job_name: movie-recommender-drift
    metrics_path: /drift-metrics
    scrape_interval: 30s
    static_configs:
      - targets: ["api:8000"]
